### ISSUE TITLE
.py script

### ISSUE THREAD

**Issue by EduardTalianu** [SinatrasC/entropix-smollm#1]
Can you create a .py script? I've tried but got weird errors but maybe because i've run in a non gpu environ

**Comment by SinatrasC** [comment]
Sure added to list it will be done after current tuning operations done

**Comment by SinatrasC** [comment]
@EdwardDali Could you test with latest packaging on uv could be fixing your issues

**Comment by EduardTalianu** [comment]
thanks, I will look into it. fyi, in the meantime I've created this https://github.com/EdwardDali/EntropixLab

**Comment by SinatrasC** [comment]
are you using quantized gguf models ?

**Comment by EduardTalianu** [comment]
> are you using quantized gguf models ?

in the second branch, yes. the dinamic sampling seems to work but I can't calculate the attention entropy, seems that is not possible

**Comment by SinatrasC** [comment]
Yes that was the point i will mention you can have some problems getting some metrics in strategies but good work overall

**Comment by EduardTalianu** [comment]
you can somehow approximate the attention entropy using other factors like the varuance of the entropy over a window of tokens and could make it more stable using a chunking strategy before changing the strategy but overall it's not a stable, consistent result. the attention entropy seems to be needed at the moment this is why I moved the non-gguf branch as main

**Comment by SinatrasC** [comment]
CLI version is implemented
